### ISSUE TITLE
Wrong color for parameter named "continue"

### ISSUE THREAD

**Issue by LinusU** [textmate/swift.tmbundle#34]
First of all, I noticed this in VS Code with the default syntax highlighting, terribly sorry if this is not the correct repo to report to 🙈 

<img width="381" alt="screen shot 2018-04-20 at 11 35 51" src="https://user-images.githubusercontent.com/189580/39046755-2f70be34-448f-11e8-8491-4723a325ae94.png">

Pasted in the following:

```swift
optional func application(_ application: UIApplication, 
                 continue userActivity: NSUserActivity, 
       restorationHandler: @escaping ([Any]?) -> Void) -> Bool
```

and started googling what the `continue` keyword meant for a function parameter 😂

**Comment by jtbandes** [comment]
No, this is handled fine by Swift.tmbundle:

<img src="https://user-images.githubusercontent.com/14237/39097962-69b5435a-4618-11e8-9a4a-81e8474c6980.png" width="500">

(In fact, GitHub syntax highlighting also uses this bundle, so your code sample above is enough to see that it is working 😉)

**Comment by LinusU** [comment]
Sorry 🙈 I'll dig deeper

**Comment by infininight** [comment]
In many cases VSCode does use the TextMate grammar versions but in this case it uses:

https://github.com/freebroccolo/atom-language-swift

It is no longer maintained though so you may need to ask VSCode support to switch to a more maintained grammar or see if someone wants to take up maintenance otherwise.
